In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv('customer_shopping_behavior.csv')

In [3]:
df.head(10)

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually
5,6,46,Male,Sneakers,Footwear,20,Wyoming,M,White,Summer,2.9,Yes,Standard,Yes,Yes,14,Venmo,Weekly
6,7,63,Male,Shirt,Clothing,85,Montana,M,Gray,Fall,3.2,Yes,Free Shipping,Yes,Yes,49,Cash,Quarterly
7,8,27,Male,Shorts,Clothing,34,Louisiana,L,Charcoal,Winter,3.2,Yes,Free Shipping,Yes,Yes,19,Credit Card,Weekly
8,9,26,Male,Coat,Outerwear,97,West Virginia,L,Silver,Summer,2.6,Yes,Express,Yes,Yes,8,Venmo,Annually
9,10,57,Male,Handbag,Accessories,31,Missouri,M,Pink,Spring,4.8,Yes,2-Day Shipping,Yes,Yes,4,Cash,Quarterly

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [5]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.068462,59.764359,3.750065,25.351538
std,1125.977353,15.207589,23.685392,0.716983,14.447125
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,39.000000,3.100000,13.000000
50%,1950.500000,44.000000,60.000000,3.800000,25.000000
75%,2925.250000,57.000000,81.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x : x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')
df = df.rename(columns={'purchase_amount_(usd)':'purchase_amaount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amaount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

Feature Engineering

In [11]:
# create age_group columns based on age column

lables = ['Young-Adult','Adult','Middle-ages','Senior']

df['age_group'] = pd.qcut(df['age'] , q = 4 , labels=lables)

In [12]:
df.groupby('age_group')['age'].max()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_21024\1230913677.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('age_group')['age'].max()

age_group
Young-Adult    31
Adult          44
Middle-ages    57
Senior         70
Name: age, dtype: int64

In [13]:
df['frequency_of_purchases'].unique()

array(['Fortnightly', 'Weekly', 'Annually', 'Quarterly', 'Bi-Weekly',
       'Monthly', 'Every 3 Months'], dtype=object)

In [14]:
# create purchase_frequency_days

frequency_mapping = {
                    'Fortnightly':14, 
                     'Weekly':7, 
                     'Annually':365, 
                     'Quarterly':90, 
                     'Bi-Weekly':14,
                     'Monthly':30,
                     'Every 3 Months':90
                     }

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amaount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_frequency_days
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-ages,14
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young-Adult,14
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-ages,7
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young-Adult,7
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-ages,365

In [15]:
df[['purchase_frequency_days' , 'frequency_of_purchases']]

      purchase_frequency_days frequency_of_purchases
0                          14            Fortnightly
1                          14            Fortnightly
2                           7                 Weekly
3                           7                 Weekly
4                         365               Annually
...                       ...                    ...
3895                        7                 Weekly
3896                       14              Bi-Weekly
3897                       90              Quarterly
3898                        7                 Weekly
3899                       90              Quarterly

[3900 rows x 2 columns]

In [16]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [17]:
# remove column = promo_code_used 

df = df.drop('promo_code_used',axis=1)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customer_id              3900 non-null   int64
 1   age                      3900 non-null   int64
 2   gender                   3900 non-null   object
 3   item_purchased           3900 non-null   object
 4   category                 3900 non-null   object
 5   purchase_amaount         3900 non-null   int64
 6   location                 3900 non-null   object
 7   size                     3900 non-null   object
 8   color                    3900 non-null   object
 9   season                   3900 non-null   object
 10  review_rating            3900 non-null   float64
 11  subscription_status      3900 non-null   object
 12  shipping_type            3900 non-null   object
 13  discount_applied         3900 non-null   object
 14  previous_purchases       3900 non-null   int64
 15  payment_method           3900 non-null   object
 16  frequency_of_purchases   3900 non-null   object
 17  age_group                3900 non-null   category
 18  purchase_frequency_days  3900 non-null   int64
dtypes: category(1), float64(1), int64(5), object(12)
memory usage: 552.6+ KB

#### Connecting python script to PostgreSQL

In [ ]:
# %pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\lenovo\anaconda3\lib\site-packages (2.9.13)Note: you may need to restart the kernel to use updated packages.

Requirement already satisfied: sqlalchemy in c:\users\lenovo\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)

In [ ]:
# from sqlalchemy import create_engine

# username = " "
# password = " "
# host = "localhost"
# port = "5432"
# database = "customer_behavior"

# engine = create_engine(
#     f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
#     )

# # load dataframe into PostgreSQL

# table_name = 'customer'
# df.to_sql(table_name,engine,if_exists = 'replace' , index = False)

# print(f"Data successfully loaded into the '{table_name}' in database '{database}")

Data successfully loaded into the 'customer' in database 'customer_behavior